name: Generate API Docs

on:
  push:
    branches:
      - master
jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node environment  
      uses: actions/setup-node@v4
      with:
        node-version: '16.x'

    - name: Install spectaql
      run: npm install -g spectaql
    
    - name: Gen docs
      run: npx spectaql src/spectaql.yml

    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: master
        folder: docs